name: Build PyInjector for Windows x64

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]  # Windows 10/11 兼容的 runner
        arch: [x64]  # 仅构建 64 位；添加 'x86' 以扩展
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: false  # 如果有子模块，设为 true

    - name: Setup MSVC and Visual Studio
      uses: microsoft/setup-msbuild@v2  # 设置 MSBuild（用于 .sln/.vcxproj）

    - name: Restore NuGet packages (if any)
      run: nuget restore  # 如果项目有 NuGet 依赖，跳过此步或调整路径

    - name: Build project (x64 Release)
      run: |
        # 假设解决方案文件名为 PyInjector.sln；调整为实际文件名
        msbuild PyInjector.sln /p:Configuration=Release /p:Platform=${{ matrix.arch }} /t:Rebuild /m
        # 输出路径示例：x64/Release/PyInjector.dll
      env:
        # 如果需要 Python 头文件，添加 Python 安装（可选）
        PYTHON_VERSION: '3.12'  # 根据项目支持版本调整

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PyInjector-${{ matrix.arch }}-DLL
        path: |
          ${{ matrix.arch }}/Release/*.dll
          ${{ matrix.arch }}/Release/*.pdb  # 可选：调试符号
        retention-days: 30  # 保留 30 天

    - name: List build output (for debugging)
      if: always()
      run: dir ${{ matrix.arch }}\Release\ /s  # Windows 命令，列出输出文件
